name: instances
version: '0.1.0.0'
category: foo
author: Carl Hedgren
maintainer: example@example.com
copyright: 2017 Carl Hedgren
license: BSD3
github: githubuser/instances
extra-source-files:
- README.md
default-extensions:
- InstanceSigs
library:
  source-dirs: src
  exposed-modules:
  - Perhaps
  - Or
  - Items
  - Steit
  - Two
  dependencies:
  - base >=4.7 && <5
tests:
  instances-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -freverse-errors
    dependencies:
    - base
    - instances
    - QuickCheck
    - checkers
